### PR TITLE
Add support for GraphQL

### PR DESCRIPTION
**Pull request by bradleyayers**

### CODE REVIEW

**Comment by stkb** [comment]
Perfect, thanks! Will publish this weekend.

**Comment by stkb** [comment]
Have added the `.gql` extension too. From reading, some still use this, although `.graphql` is the recommended.

**Comment by bradleyayers** [comment]
The `.gql` addition is pragmatic (I was actually using that extension in my project until I did some research for this PR).

I figured I'd leave it out of Rewrap and rely on the language detection instead (my understanding was that it'd be better to rely on VS Code's extension->language mapping rather than duplicating it here). I'm curious why that's not sufficient in general actually? (i.e. just utilising VS Code's language detection)

**Comment by stkb** [comment]
It always checks the language id first for a match. The file extensions are just a backup because I wanted it to still work even if the user doesn't have any extension installed for that language.

**Pull request merged**
